### ISSUE TITLE
Remote can get stuck in one mode for Volvo 6x6 Hauler

### ISSUE THREAD

**Issue by piotrmil** [repkovsky/technic#1]
So, I was very eager to try this amazing code for Volvo 6x6 hauler, and at first, it worked like a charm!

But then... I did something, and I'm not sure what, but it kinda made the remote stuck in one gear.  I can go up, but not down anymore, until I reset the whole thing. Also, the dumper now lowers on red light setting instead of green... 

I do apologise for very  sparse bug report, but all I  am saying is, it is possible to get the remote "confused" with options.

**Comment by repkovsky** [comment]
Thanks for the feedback. 

- First, check whether the gearbox calibrates properly - after the remote is connected, it should move maximally to the left, to the position visible for example here https://youtu.be/kKGAsx_oDbM?t=844. In principle, gearbox is calibrated by turning the L motor left, until it meets resistance and stops. This point is considered to be 1st gear. If it stops earlier than that, it will not operate properly. 
- If it does stop at right point, check whether in manual mode, the violet element moves by 90 degrees, when switching gears. In the case of my 42114 set it was sufficient just to send command to increase angle by 90 degrees, and it was also 90 degrees in reality, but I don't know, maybe different motors have different measurements of angle and reality is different than what is commanded.

I am looking forward to your response, I hope I will be able to improve the program.

**Comment by piotrmil** [comment]
Yeah, there is something wrong with the calibrtion- it is not performed. I am sure it did the first time, though.

And also now the dumper controls are swapped: + brings it down, - Up.

**Comment by repkovsky** [comment]
I have submitted a new version with the improved calibration - you can test whether this fixed the problem in your case.

**Comment by piotrmil** [comment]
That seems to have done the trick! Now the purple element resets to proper position at the start. Thanks!
