### ISSUE TITLE
Worked fine untill....

### ISSUE THREAD

**Issue by Fliflaflo** [repkovsky/technic#3]
Had great fun and also added some lights.. made sure it connected to a dedicated and named remote.
Since today it stopped working and comes back with the following issue..

Remote connected.
Traceback (most recent call last):
  File "main.py", line 189, in <module>
  File "main.py", line 50, in __init__
  File "main.py", line 58, in calibrate
ValueError: Invalid argument

Also going back to the unadapted original code  gives the same invallid arguments...
It worked fine for a week.. Please advise! really liked your work on this model!

**Comment by Fliflaflo** [comment]
> Had great fun and also added some lights.. made sure it connected to a dedicated and named remote. Since today it stopped working and comes back with the following issue..
> 
> Remote connected. Traceback (most recent call last): File "main.py", line 189, in File "main.py", line 50, in **init** File "main.py", line 58, in calibrate ValueError: Invalid argument
> 
> Also going back to the unadapted original code gives the same invallid arguments... It worked fine for a week.. Please advise! really liked your work on this model!

Rebooted the lego app and again the pybricks app... problem seems to be solved... works again including the lighting...

**Comment by repkovsky** [comment]
Great! Nevertheless thank you for opening the issue (I was just about to check everything once again) and don't hesitate to write in case of any problem!
